In [4]:
import numpy as np

In [37]:
print(np.arange(5))
print(1 + np.arange(5))
print(5 * np.arange(5))
print(0b10 & np.arange(5))
print(np.arange(6).reshape(2,3))

[0 1 2 3 4]
[1 2 3 4 5]
[ 0  5 10 15 20]
[0 0 2 2 0]
[[0 1 2]
 [3 4 5]]


In [17]:
n = 3
for k in range(-n+1,n):
    ones = np.ones(n-abs(k), dtype=np.float64)
    # k controls which diagonal is used
    print(np.diag(ones, k=k))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
m = np.arange(6).reshape((2,3))
print(m)
# If argument to diag is 1D return 2D, with the entries along the leading diagonal
# If argument is 2D, return the leading diagonal (1D)
# Works on non-square matrices too
print(np.diag(m))

[[0 1 2]
 [3 4 5]]
[0 4]


In [45]:
print(m)
print(np.zeros_like(m))
print(np.ones_like(m))
print(np.random.rand(3, 2)) # Raw arguments, not tuple

[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[0.83091504 0.06787112]
 [0.32085223 0.36312516]
 [0.25933317 0.31290935]]


In [35]:
print(np.ones(3, dtype=np.float64))
print(np.zeros((3, 3), dtype=np.float32))
print(np.zeros((2, 2, 2), dtype=np.int8))

[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
